"""Export real hourly station data for the Pink Monster demo (web/dist/data/maitri-2023.js).

Weather is ERA5 reanalysis at Maitri (-70.7667, 11.7333) for 2023, from the committed
Parquet cache. Solar and wind come from the engine's physics model on that weather
(pvlib plane-of-array PV with snow cover; manufacturer power curve with air density and
icing), expressed per installed kW so the demo's capacity inputs scale real output exactly.

Load comes from the engine's physics model with NO random component: the model's domestic
and workshop variation terms are replaced by their expected values, so every number here is
either measured weather or a deterministic function of it.

    python export_demo_weather.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))

from polarems.availability import apply_availability  # noqa: E402
from polarems.config import load_config  # noqa: E402
from polarems.twin import build_loads, pv_potential, wind_potential  # noqa: E402
from polarems.weather import fetch_year  # noqa: E402

OUT = ROOT.parent / "web" / "dist" / "data" / "maitri-2023.js"
START = "2023-05-01"          # start of the polar winter
MAX_DAYS = 210                # the demo's longest mission
HORIZON_H = 36                # planner look-ahead beyond the last mission hour
HISTORY_H = 24                # the day before the mission, for the same-hour-yesterday forecast


class ExpectedValue:
    """Stands in for a random generator: every draw returns the distribution's mean."""

    def normal(self, loc=0.0, scale=1.0, size=None):
        return np.full(size, float(loc))

    def uniform(self, low=0.0, high=1.0, size=None):
        return np.full(size, (float(low) + float(high)) / 2)


def main() -> int:
    cfg = load_config()
    weather = fetch_year(cfg["station.latitude"], cfg["station.longitude"], 2023)

    df = weather.copy().join(build_loads(weather, cfg, ExpectedValue()))
    df["pv_potential_kw"] = pv_potential(weather, cfg).to_numpy()
    df["wind_potential_kw"] = wind_potential(weather, cfg).to_numpy()
    df = apply_availability(df, cfg)

    hours = HISTORY_H + MAX_DAYS * 24 + HORIZON_H
    win = df.loc[pd.Timestamp(START) - pd.Timedelta(hours=HISTORY_H):].head(hours)
    if len(win) < hours:
        raise SystemExit(f"only {len(win)} hours available after {START}; need {hours}")

    pv_kwp = float(cfg["pv.kwp"])
    wind_kw = float(cfg["wind.rated_kw"]) * int(cfg["wind.n_turbines"])

    def col(series, nd):
        return [round(float(v), nd) for v in series.to_numpy()]

    data = {
        "start": f"{START}T00:00Z",
        "history": HISTORY_H,
        "hours": hours,
        "source": "ERA5 reanalysis (ECMWF/Copernicus), hourly, Maitri station grid point (-70.75, 11.75), 2023",
        "model": "Solar, wind and demand from the HIMSHAKTI engine's physics model of the station",
        "temperature": col(win["temp_c"], 1),
        "windSpeed": col(win["wind_ms"], 1),
        "pvPerKw": col(win["pv_kw"] / pv_kwp, 4),
        "windPerKw": col(win["wind_kw"] / wind_kw, 4),
        "load": col(win["load_kw"], 2),
        "critical": col(win["load_critical_kw"], 2),
        "essential": col(win["load_essential_kw"], 2),
        "domestic": col(win["load_deferrable_kw"] + win["load_sheddable_kw"], 2),
    }
    # the three tiers must add up to total demand
    gap = max(abs(c + e + d - l) for c, e, d, l in zip(data["critical"], data["essential"], data["domestic"], data["load"]))
    assert gap < 0.05, f"tiers do not sum to load (max gap {gap})"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(data, separators=(",", ":"))
    OUT.write_text(
        "// Real hourly station data for Maitri, Antarctica. Generated by engine/export_demo_weather.py.\n"
        "// Weather: ERA5 reanalysis. Solar, wind and demand: deterministic physics model of the station.\n"
        f"export const STATION = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({OUT.stat().st_size / 1e3:,.0f} KB, {hours} h from {START})")
    print(f"  mean load {np.mean(data['load']):.1f} kW, critical {np.mean(data['critical']):.1f} kW, "
          f"essential {np.mean(data['essential']):.1f} kW, domestic {np.mean(data['domestic']):.1f} kW")
    print(f"  mean temperature {np.mean(data['temperature']):.1f} C, "
          f"PV capacity factor {np.mean(data['pvPerKw']):.3f}, wind capacity factor {np.mean(data['windPerKw']):.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
